#cloud-config
autoinstall:
  version: 1
  locale: pl_PL
  keyboard:
    layout: pl
  identity:
    hostname: ubuntu
    username: lukinio
    password: "$6$ldU404.TTvzf.Jma$05HY49JGX1lmTiwH0s3Q5fpiXZBRHsrDsK2Maw69jr38GvSn6pqz3x.buQ7gFTPVKgd4lcA.YQDtS04Kkbmt90"

  storage:
    config:
      # 1) Disk and partitions
      - type: disk
        id: disk0
        match:
          size: largest
        ptable: gpt
        wipe: superblock-recursive

      - type: partition
        id: partition-efi
        device: disk0
        size: 512M
        # Correct key is 'flags:', not 'flag:'
        flags: [ boot, esp ]

      - type: partition
        id: partition-boot
        device: disk0
        size: 1G
        # If you want a boot flag, use flags: [ boot ]
        flags: [ boot ]

      - type: partition
        id: partition-lvm
        device: disk0
        size: -1

      # 2) Format + mount EFI partition
      - type: format
        id: format-efi
        volume: partition-efi        # <-- use 'volume:' not 'device:'
        fstype: fat32
        label: EFI

      - type: mount
        path: /boot/efi
        device: format-efi

      # 3) Format + mount /boot
      - type: format
        id: format-boot
        volume: partition-boot
        fstype: ext4
        label: boot

      - type: mount
        path: /boot
        device: format-boot

      # 4) LVM setup: define volumes only
      - type: lvm_volumes
        id: lvm0
        volgroup: ubuntu-vg
        devices: [ partition-lvm ]
        volumes:
          - name: root
            size: 50%
          - name: var
            size: 15%
          - name: home
            size: 15%
          - name: tmp
            size: 5%
          - name: swap
            size: 15%

      # 5) Format + mount each LVM volume
      - type: format
        id: format-root
        volume: lvm0/root
        fstype: ext4
      - type: mount
        path: /
        device: format-root

      - type: format
        id: format-var
        volume: lvm0/var
        fstype: ext4
      - type: mount
        path: /var
        device: format-var
        options: [defaults, noexec, nodev, nosuid]

      - type: format
        id: format-home
        volume: lvm0/home
        fstype: ext4
      - type: mount
        path: /home
        device: format-home
        options: [defaults, noexec, nodev, nosuid]

      - type: format
        id: format-tmp
        volume: lvm0/tmp
        fstype: ext4
      - type: mount
        path: /tmp
        device: format-tmp
        options: [defaults, noexec, nodev, nosuid]

      # 6) Format swap volume (no mount for swap)
      - type: format
        id: format-swap
        volume: lvm0/swap
        fstype: swap

  packages: []
