#cloud-config
autoinstall:
  version: 1
  locale: pl_PL
  keyboard:
    layout: pl
  identity:
    hostname: ubuntu
    username: lukinio
    password: "$6$ldU404.TTvzf.Jma$05HY49JGX1lmTiwH0s3Q5fpiXZBRHsrDsK2Maw69jr38GvSn6pqz3x.buQ7gFTPVKgd4lcA.YQDtS04Kkbmt90"
  storage:
    config:
      - type: disk
        id: disk0
        match:
          # ssd: true
          size: largest
        path: /dev/sda
        ptable: gpt
        wipe: superblock-recursive
      - type: partition
        id: partition-efi
        device: disk0
        size: 512M
        flag: [ boot, esp ]
      - type: partition
        id: partition-boot
        device: disk0
        size: 1G
        flag: [ boot ]
      - type: partition
        id: partition-lvm
        device: disk0
        size: -1
      - type: format
        id: format-efi
        device: partition-efi
        fstype: fat32
        label: EFI
      - type: mount
        id: mount-efi
        device: format-efi
        path: /boot/efi
      - type: format
        id: format-boot
        device: partition-boot
        fstype: ext4
        label: boot
      - type: mount
        id: mount-boot
        device: format-boot
        path: /boot
      - type: lvm_volumes
        id: lvm0
        volgroup: ubuntu-vg
        devices: [ partition-lvm ]
        volumes:
          - name: root
            size: 50%
            mount:
              mount_point: /
              format: ext4
              options: [defaults]
          - name: var
            size: 15%
            mount:
              mount_point: /var
              format: ext4
              options: [defaults, noexec, nodev, nosuid]
          - name: home
            size: 15%
            mount:
              mount_point: /home
              format: ext4
              options: [defaults, noexec, nodev, nosuid]
          - name: tmp
            size: 5%
            mount:
              mount_point: /tmp
              format: ext4
              options: [defaults, noexec, nodev, nosuid]
          - name: swap
            size: 15%
  packages: []
