#cloud-config
autoinstall:
  version: 1
  locale: pl_PL
  keyboard:
    layout: pl
  identity:
    hostname: ubuntu
    username: lukinio
    password: "$6$ldU404.TTvzf.Jma$05HY49JGX1lmTiwH0s3Q5fpiXZBRHsrDsK2Maw69jr38GvSn6pqz3x.buQ7gFTPVKgd4lcA.YQDtS04Kkbmt90"

  storage:
    config:
      # 1) Select the disk
      - type: disk
        id: disk0
        match:
          size: largest
        ptable: gpt
        wipe: superblock-recursive

      # 2) EFI partition
      - type: partition
        id: partition-efi
        device: disk0
        size: 512M
        flags: [ boot, esp ]

      # 3) /boot partition
      - type: partition
        id: partition-boot
        device: disk0
        size: 1G
        flags: [ boot ]

      # 4) LVM partition
      - type: partition
        id: partition-lvm
        device: disk0
        size: -1

      # 5) Format + mount EFI
      - type: format
        id: format-efi
        volume: partition-efi        # <-- use 'volume:' not 'device:'
        fstype: fat32
      - type: mount
        device: partition-efi
        path: /boot/efi

      # 6) Format + mount /boot
      - type: format
        id: format-boot
        volume: partition-boot
        fstype: ext4
      - type: mount
        device: partition-boot
        path: /boot

      # 7) Define LVM volumes (no inline mount or format)
      - type: lvm_volumes
        id: lvm0
        volgroup: ubuntu-vg
        devices: [ partition-lvm ]
        volumes:
          - name: root
            size: 50%
          - name: var
            size: 15%
          - name: home
            size: 15%
          - name: tmp
            size: 5%
          - name: swap
            size: 15%

      # 8) Format + mount each LVM volume
      - type: format
        id: format-root
        volume: lvm0/root
        fstype: ext4
      - type: mount
        device: format-root
        path: /

      - type: format
        id: format-var
        volume: lvm0/var
        fstype: ext4
      - type: mount
        device: format-var
        path: /var
        options: [ defaults, noexec, nodev, nosuid ]

      - type: format
        id: format-home
        volume: lvm0/home
        fstype: ext4
      - type: mount
        device: format-home
        path: /home
        options: [ defaults, noexec, nodev, nosuid ]

      - type: format
        id: format-tmp
        volume: lvm0/tmp
        fstype: ext4
      - type: mount
        device: format-tmp
        path: /tmp
        options: [ defaults, noexec, nodev, nosuid ]

      # 9) Format swap (no mount step)
      - type: format
        id: format-swap
        volume: lvm0/swap
        fstype: swap

  packages: []
