#cloud-config
autoinstall:
  version: 1
  locale: pl_PL
  keyboard:
    layout: pl
  identity:
    hostname: ubuntu
    username: lukinio
    password: "$6$ldU404.TTvzf.Jma$05HY49JGX1lmTiwH0s3Q5fpiXZBRHsrDsK2Maw69jr38GvSn6pqz3x.buQ7gFTPVKgd4lcA.YQDtS04Kkbmt90"
  storage:
    config:
      # --- Disk and partitioning ---
      - type: disk
        id: disk0
        match:
          size: largest
        path: /dev/sda
        ptable: gpt
        wipe: superblock-recursive
      - type: partition
        id: partition-efi
        device: disk0
        size: 512M
        flag: [ boot, esp ]
      - type: partition
        id: partition-boot
        device: disk0
        size: 1G
        flag: [ boot ]
      - type: partition
        id: partition-lvm
        device: disk0
        size: -1
      - type: format
        id: format-efi
        device: partition-efi
        fstype: fat32
        label: EFI
      - type: mount
        id: mount-efi
        device: format-efi
        path: /boot/efi
      - type: format
        id: format-boot
        device: partition-boot
        fstype: ext4
        label: boot
      - type: mount
        id: mount-boot
        device: format-boot
        path: /boot

      # --- LVM volumes definition (no inline mounts) ---
      - type: lvm_volumes
        id: lvm0
        volgroup: ubuntu-vg
        devices: [ partition-lvm ]
        volumes:
          - name: root
            size: 50%
          - name: var
            size: 15%
          - name: home
            size: 15%
          - name: tmp
            size: 5%
          - name: swap
            size: 15%
            swap: true

      # --- Format and mount LVM volumes ---
      - type: format
        id: format-root
        device: lvm0/root
        fstype: ext4
      - type: mount
        id: mount-root
        device: format-root
        path: /
        options: [defaults]
      - type: format
        id: format-var
        device: lvm0/var
        fstype: ext4
      - type: mount
        id: mount-var
        device: format-var
        path: /var
        options: [defaults, noexec, nodev, nosuid]
      - type: format
        id: format-home
        device: lvm0/home
        fstype: ext4
      - type: mount
        id: mount-home
        device: format-home
        path: /home
        options: [defaults, noexec, nodev, nosuid]
      - type: format
        id: format-tmp
        device: lvm0/tmp
        fstype: ext4
      - type: mount
        id: mount-tmp
        device: format-tmp
        path: /tmp
        options: [defaults, noexec, nodev, nosuid]
