#cloud-config
autoinstall:
    version: 1
    timezone: Europe/Warsaw
    locale: pl_PL
    keyboard:
        layout: pl
    identity:
        hostname: ubuntu
        username: lukinio
        password: "$6$ldU404.TTvzf.Jma$05HY49JGX1lmTiwH0s3Q5fpiXZBRHsrDsK2Maw69jr38GvSn6pqz3x.buQ7gFTPVKgd4lcA.YQDtS04Kkbmt90"

    storage:
        swap:
            size: 0        # disable default swap
        config:
            # Wipe /dev/sda and use GPT
            -
                type: disk
                id: disk0
                match:
                    size: largest
                ptable: gpt
                wipe: superblock-recursive
                grub_device: true

            # BIOS Boot Partition (1MiB)
            -
                type: partition
                id: partition-bios
                device: disk0
                size: 1M
                flag: bios_grub

            # EFI partition (512MiB)
            -
                type: partition
                id: partition-efi
                device: disk0
                size: 512M
                flag: esp
            -
                type: format
                id: format-efi
                volume: partition-efi
                fstype: fat32
                label: EFI
            -
                type: mount
                id: mount-efi
                device: format-efi
                path: /boot/efi

            # Boot partition (1 GiB)
            -
                type: partition
                id: partition-boot
                device: disk0
                size: 1G
                flag: boot
            -
                type: format
                id: format-boot
                volume: partition-boot
                fstype: ext4
                label: BOOT
            -
                type: mount
                id: mount-boot
                device: format-boot
                path: /boot

            # Swap partition
            -
                type: partition
                id: partition-swap
                device: disk0
                size: 4G
            -
                type: format
                id: fs-swap
                volume: partition-swap
                fstype: swap

            # Logical Volume partition
            -
                type: partition
                id: partition-lvm
                device: disk0
                size: -1

            # Create the VG on the LVM partition
            -
                type: lvm_volgroup
                id: vg0
                name: VX
                devices: [ partition-lvm ]

            # Logical Volume: root (50%)
            -
                type: lvm_partition
                id: lv-root
                name: root
                volgroup: vg0
                size: 50%
            -
                type: format
                id: fs-root
                volume: lv-root
                fstype: ext4
            -
                type: mount
                id: mount-root
                device: fs-root
                path: /

            # Logical Volume: /var (15%)
            -
                type: lvm_partition
                id: lv-var
                name: var
                volgroup: vg0
                size: 15%
            -
                type: format
                id: fs-var
                volume: lv-var
                fstype: ext4
            -
                type: mount
                id: mount-var
                device: fs-var
                path: /var
                options: "nodev,nosuid"

            # Logical Volume: /var/log (10%)
            -
                type: lvm_partition
                id: lv-var-log
                name: var-log
                volgroup: vg0
                size: 10%
            -
                type: format
                id: fs-var-log
                volume: lv-var-log
                fstype: ext4
            -
                type: mount
                id: mount-var-log
                device: fs-var-log
                path: /var/log
                options: "noexec,nodev,nosuid"

            # Logical Volume: /home (20%)
            -
                type: lvm_partition
                id: lv-home
                name: home
                volgroup: vg0
                size: 20%
            -
                type: format
                id: fs-home
                volume: lv-home
                fstype: ext4
            -
                type: mount
                id: mount-home
                device: fs-home
                path: /home
                options: "nodev,nosuid"

            # Logical Volume: /tmp (5%)
            -
                type: lvm_partition
                id: lv-tmp
                name: tmp
                volgroup: vg0
            -
                type: format
                id: fs-tmp
                volume: lv-tmp
                fstype: ext4
            -
                type: mount
                id: mount-tmp
                device: fs-tmp
                path: /tmp
                options: "noexec,nodev,nosuid"

    packages: []
